num=25
print(num)
print(type(num))
num=25.5
print(num)
print(type(num))
num="25"
print(num)
print(type(num))
age=21
print(age)
print(type(age))
height=5.8
print(height)
print(type(height))
variable=Arun
print(variable)
print(type(variable))
age=20
print(age)
price=99.5
print(price)
name=Ravi
print(name)
marks=90
print(marks)
print(type(marks))
temperature=36.5
print(temperature)
print(type(temperature))
message="Welcome"
print(message)
print(type(message))
